# Generated by Django 5.1.7 on 2025-03-24 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=datetime.datetime(2025, 3, 24, 19, 0, 12, 162666))),
                ('word', models.TextField(max_length=100)),
                ('translation', models.TextField(max_length=100)),
                ('example', models.TextField(max_length=200)),
                ('genus', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Neutral'), (4, 'Plural')], null=True)),
                ('theme', models.ManyToManyField(related_name='words', to='word_collection.theme')),
            ],
        ),
    ]
