# Generated by Django 5.1.7 on 2025-03-25 07:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='theme',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='genus',
            new_name='genus_id',
        ),
        migrations.AddField(
            model_name='word',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 7, 36, 57, 830672)),
        ),
    ]
