# Generated by Django 5.1.7 on 2025-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_collection', '0006_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.IntegerField(choices=[(1, 'Noun'), (2, 'Verb'), (3, 'Adjective'), (4, 'Pronoun'), (5, 'Adverb'), (6, 'Preposition'), (7, 'Number'), (8, 'Article'), (9, 'Conjunction'), (10, 'Interjection')], null=True),
        ),
    ]
