# Generated by Django 5.1.7 on 2025-04-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_collection', '0008_remove_word_example_remove_word_translation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='part_of_speech',
            new_name='part_of_speech_id',
        ),
    ]
