# Generated by Django 5.1.7 on 2025-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_collection', '0009_rename_part_of_speech_word_part_of_speech_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='usage_variants',
        ),
        migrations.AddField(
            model_name='word',
            name='prepositions_and_cases_with_translations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='word',
            name='other_forms',
            field=models.JSONField(default=list),
        ),
    ]
