# Generated by Django 5.1.7 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_collection', '0011_alter_category_owner_alter_word_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.TextField(default='#EACB00', max_length=10),
        ),
    ]
