# Generated by Django 5.1.7 on 2026-07-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_collection", "0012_category_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="word",
            name="examples",
        ),
        migrations.RemoveField(
            model_name="word",
            name="other_forms",
        ),
        migrations.RemoveField(
            model_name="word",
            name="prepositions_and_cases_with_translations",
        ),
        migrations.RemoveField(
            model_name="word",
            name="translations",
        ),
        migrations.RemoveField(
            model_name="word",
            name="usage_count",
        ),
        migrations.AddField(
            model_name="word",
            name="image_url",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="WordExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField(max_length=200)),
                ("translation", models.TextField(max_length=200)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="word_collection.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("form", models.TextField(max_length=100)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="word_collection.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordPrepositionAndCaseWithTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preposition", models.TextField(max_length=100)),
                ("case", models.TextField(max_length=100)),
                ("translation", models.TextField(max_length=100)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepositions_and_cases_with_translations",
                        to="word_collection.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.TextField(max_length=100)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="word_collection.word",
                    ),
                ),
            ],
        ),
    ]
