# Generated by Django 5.1.7 on 2026-07-20 17:08

import django.db.models.deletion
import word_collection.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "word_collection",
            "0013_remove_word_categories_remove_word_examples_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        default=word_collection.utils.get_superuser_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=200, null=True)),
                ("image_url", models.TextField(max_length=200, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=word_collection.utils.get_superuser_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        related_name="collections", to="word_collection.word"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="collections", to="word_collection.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
