# Generated by Django 5.1.7 on 2026-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_collection", "0014_tag_collection_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="background_color",
            field=models.TextField(max_length=7, null=True),
        ),
    ]
